language: go
go:
  - 1.10.x
  - 1.9.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - docker-compose -f testdata/docker-compose-${KAFKA_VERSION}.yml up -d
  - sleep 15
script:
  - make default test-race
services:
  - docker
env:
  - KAFKA_VERSION=2.0.x
  - KAFKA_VERSION=1.1.x
  - KAFKA_VERSION=1.0.x
  - KAFKA_VERSION=0.11.x
